'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('scout', [{
      block_id: 5,
      bed_id: 1,
      station_id: 1,
      point_id: 1,
      created_by: 3,
      modified_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
      scout_date: "2020-01-08 09:44:48",
      issue_type_id: 2,
      issue_id: 1,
      issue_category_id: null,
      scout_value: 4,
      plant_id: 1,
      variety_id: 1,
      scout_longitude: "37.0110113",
      scout_latitude: "-0.1092173",
      tolerance_id: 1
    }, {
      block_id: 5,
      bed_id: 1,
      station_id: 1,
      point_id: 1,
      created_by: 3,
      modified_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
      scout_date: "2020-01-08 09:44:48",
      issue_type_id: 2,
      issue_id: 1,
      issue_category_id: null,
      scout_value: 4,
      plant_id: 1,
      variety_id: 1,
      scout_longitude: "37.0110113",
      scout_latitude: "-0.1092173",
      tolerance_id: 1
    }, {
      block_id: 5,
      bed_id: 1,
      station_id: 2,
      point_id: 2,
      created_by: 3,
      modified_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
      scout_date: "2020-01-08 09:45:07",
      issue_type_id: 1,
      issue_id: 1,
      issue_category_id: 1,
      scout_value: 1,
      plant_id: 1,
      variety_id: 1,
      scout_longitude: "37.0110113",
      scout_latitude: "-0.1092173",
      tolerance_id: 1
    }, {
      block_id: 5,
      bed_id: 1,
      station_id: 3,
      point_id: 2,
      created_by: 3,
      modified_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
      scout_date: "2020-01-08 09:45:31",
      issue_type_id: 1,
      issue_id: 1,
      issue_category_id: 1,
      scout_value: 1,
      plant_id: 1,
      variety_id: 1,
      scout_longitude: "37.0110113",
      scout_latitude: "-0.1092173",
      tolerance_id: 1
    }, {
      block_id: 5,
      bed_id: 1,
      station_id: 4,
      point_id: 4,
      created_by: 3,
      modified_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
      scout_date: "2020-01-08 09:45:56",
      issue_type_id: 1,
      issue_id: 1,
      issue_category_id: 1,
      scout_value: 1,
      plant_id: 1,
      variety_id: 1,
      scout_longitude: "37.0110113",
      scout_latitude: "-0.1092173",
      tolerance_id: 1
    }, {
      block_id: 5,
      bed_id: 1,
      station_id: 4,
      point_id: 1,
      created_by: 3,
      modified_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
      scout_date: "2020-01-08 09:44:48",
      issue_type_id: 2,
      issue_id: 1,
      issue_category_id: null,
      scout_value: 4,
      plant_id: 1,
      variety_id: 1,
      scout_longitude: "36.9875794",
      scout_latitude: "-0.0790282",
      tolerance_id: 1
    }, {
      block_id: 5,
      bed_id: 1,
      station_id: 4,
      point_id: 1,
      created_by: 3,
      modified_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
      scout_date: "2020-01-07 09:45:56",
      issue_type_id: 1,
      issue_id: 1,
      issue_category_id: 1,
      scout_value: 1,
      plant_id: 1,
      variety_id: 1,
      scout_longitude: "36.9875794",
      scout_latitude: "-0.0790282",
      tolerance_id: 1
    }], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('scout', null, {});
  }
};